pipeline {
    agent any
    stages {
        stage('Deploy via SSH File') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'RASPI_IP', variable: 'IP'),
                        file(credentialsId: 'RASPI_SSH_KEY_FILE', variable: 'KEY_PATH'),
                        usernamePassword(credentialsId: 'RASPI_AUTH', usernameVariable: 'USER', passwordVariable: 'PASS')
                    ]) {
                        echo "Déploiement forcé sur ${IP}..."
                        sh """
                            chmod 600 ${KEY_PATH}
                            ssh -o StrictHostKeyChecking=no -i ${KEY_PATH} ${USER}@${IP} 'mkdir -p ~/ansible_deploy'
                            scp -o StrictHostKeyChecking=no -i ${KEY_PATH} -r ./* ${USER}@${IP}:~/ansible_deploy/
                            ssh -o StrictHostKeyChecking=no -i ${KEY_PATH} ${USER}@${IP} 'cd ~/ansible_deploy && ansible-playbook site.yml -i inventory/hosts.ini --extra-vars "ansible_sudo_pass=${PASS}"'
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}